version: "2"
run:
  modules-download-mode: readonly
linters:
  default: all
  disable:
    - revive
    - testpackage
    - varnamelen
  exclusions:
    warn-unused: true
    rules:
      - linters:
          - funlen
        path: _test.go
