issues:
  exclude-rules:
    - path: _test.go
      linters:
        - funlen

run:
  modules-download-mode: readonly

linters:
  disable:
    - testpackage
    - varnamelen
  presets:
    - bugs
    - comment
    - complexity
    - error
    - format
    - import
    - metalinter
    - module
    - performance
    - sql
    - style
    - test
    - unused

linters-settings:
  gci:
    sections:
      - standard
      - default
      - prefix(github.com/MartyHub)
    custom-order: true
